export const ACTIONS = {
  ADD_MEAL: "ADD_MEAL",
  GET_MEALS_FROM_SERVER_DONE: "GET_MEALS_FROM_SERVER_DONE",
  REMOVE_MEAL: "REMOVE_MEAL",
  CLEAR_MEALS: "CLEAR_MEALS",
  ADD_COMMENT: "ADD_COMMENT",
  PRESENT_MEAL: "PRESENT_MEAL",
  CONFIG: {
    CHANGE_STARS_COLOR: "CHANGE_STARS_COLOR",
  },
};
